# Generated by Django 5.2.2 on 2025-06-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("age", models.IntegerField()),
                ("bio", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("joined_on", models.DateTimeField(auto_now_add=True)),
                ("enrolled_courses", models.ManyToManyField(to="students.course")),
            ],
        ),
    ]
